name: Advanced Usage

on: push

jobs:
  convert_to_html:
    runs-on: ubuntu-latest
    env:
      FILE_NAME: Kento_Okamoto_Resume
    steps: 
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - run: |
          ls ${{ github.workspace }}
      - uses: docker://pandoc/core:latest
        with:
          args: >-
            --section-divs
            --from=markdown
            --to=html5
            --template=${{github.workspace}}/src/template/resume.html
            --include-in-header=${{github.workspace}}/src/styles/styles.css
            --include-before-body=${{github.workspace}}/src/header.html
            --output=${{ github.workspace }}/CV/${{env.FILENAME}}.html
      - run: echo "🍏 This job's status is ${{ job.status }}."

